apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cart.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cart.labels" . | nindent 4 }}
data:
  REDIS_HOST: {{ .Values.configMap.REDIS_HOST }}
  CATALOGUE_HOST: {{ .Values.configMap.CATALOGUE_HOST }}
  CATALOGUE_PORT: {{ .Values.configMap.CATALOGUE_PORT }}