apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "catalogue.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "catalogue.labels" .| nindent 4 }}
data:
  MONGO: "true"
  MONGO_URL: {{ .Values.configMap.MONGO_URL }}