apiVersion: v1
kind: Service
metadata:
  name: {{ include "catalogue.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "catalogue.labels" . | nindent 4 }}
spec:
  selector:
    # labels are used as selectors
    {{- include "catalogue.labels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: 8080 # servie port
    targetPort: 8080 # container port